'use client';
import { useState } from 'react'; import Link from 'next/link'; import { useRouter } from 'next/navigation';
import { useAuth } from '@/lib/auth-context'; import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Label } from '@/components/ui/label';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
export default function RegisterPage() {
  const { register } = useAuth(); const router = useRouter();
  const [form,setForm]=useState({name:'',email:'',password:''}); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  const handleSubmit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{await register(form);router.push('/dashboard');}catch(err){setError(err instanceof Error?err.message:'Kayıt başarısız');}finally{setLoading(false);}};
  return (<div className="flex min-h-screen items-center justify-center bg-kilim-pattern px-4"><Card className="w-full max-w-md"><CardHeader><CardTitle className="font-display text-2xl">KilimCraft Hesabı Oluştur</CardTitle></CardHeader><CardContent><form onSubmit={handleSubmit} className="space-y-4"><div><Label htmlFor="name">Ad Soyad</Label><Input id="name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></div><div><Label htmlFor="email">E-posta</Label><Input id="email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></div><div><Label htmlFor="password">Şifre</Label><Input id="password" type="password" minLength={6} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></div>{error&&<p className="text-sm text-destructive">{error}</p>}<Button type="submit" className="w-full text-white" disabled={loading}>{loading?'Kaydediliyor...':'Kayıt Ol'}</Button></form><p className="mt-4 text-center text-sm text-muted-foreground">Zaten hesabınız var mı? <Link href="/login" className="text-indigo hover:underline">Giriş yapın</Link></p></CardContent></Card></div>);
}
