'use client';
import { useEffect, useState } from 'react';
import { Building2, Users, Grid3X3, ClipboardList, Package, ShieldCheck } from 'lucide-react';
import { AppLayout } from '@/components/app-layout'; import { StatCard } from '@/components/stat-card';
import { LoadingSpinner, ErrorState } from '@/components/states'; import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge'; import { api } from '@/lib/api'; import { formatDate, formatWeight, formatCm, label } from '@/lib/utils';
export default function DashboardPage() {
  const [stats,setStats]=useState<any>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(false);
  const load=()=>{setLoading(true);setError(false);api.dashboard.stats().then(d=>setStats(d)).catch(()=>setError(true)).finally(()=>setLoading(false));};
  useEffect(()=>{load();},[]);
  return (<AppLayout><div className="space-y-6"><div><h1 className="font-display text-3xl font-bold">Operasyon Paneli</h1><p className="text-muted-foreground">Atölye, tezgah ve dokuma KPI özeti</p></div><div className="brutal-divider"/>{loading&&<LoadingSpinner/>}{error&&<ErrorState onRetry={load}/>}{stats&&!loading&&(<><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4"><StatCard title="Aktif Atölye" value={stats.activeWorkshops} description={`Toplam ${stats.totalWorkshops}`} icon={<Building2 className="h-5 w-5"/>}/><StatCard title="Dokumacılar" value={stats.totalWeavers} description={`${stats.masterWeavers} usta`} icon={<Users className="h-5 w-5"/>}/><StatCard title="Aktif Tezgah" value={stats.activeLooms} description={`Toplam ${stats.totalLooms}`} icon={<Grid3X3 className="h-5 w-5"/>}/><StatCard title="Bekleyen Sipariş" value={stats.pendingOrders} description={`${stats.inProgressOrders} devam ediyor`} icon={<ClipboardList className="h-5 w-5"/>}/><StatCard title="İplik Stoku" value={formatWeight(stats.yarnStockKg)} description={`${stats.totalPatterns} desen`} icon={<Package className="h-5 w-5"/>}/><StatCard title="Aylık Üretim" value={formatCm(stats.monthCmCompleted)} icon={<Grid3X3 className="h-5 w-5"/>}/><StatCard title="Kalite Puanı" value={stats.avgQualityScore} icon={<ShieldCheck className="h-5 w-5"/>}/></div><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-lg">Son Üretim Kayıtları</CardTitle></CardHeader><CardContent>{!stats.recentProductionRuns?.length?<p className="text-sm text-muted-foreground">Kayıt yok.</p>:<table className="data-table"><thead><tr><th>Tarih</th><th>cm</th><th>Durum</th></tr></thead><tbody>{stats.recentProductionRuns.map((r:any)=><tr key={r.id}><td>{formatDate(r.runDate)}</td><td>{formatCm(r.cmCompleted)}</td><td><Badge>{label('runStatus',r.status)}</Badge></td></tr>)}</tbody></table>}</CardContent></Card><Card><CardHeader><CardTitle className="text-lg">Aktif Siparişler</CardTitle></CardHeader><CardContent>{!stats.recentOrders?.length?<p className="text-sm text-muted-foreground">Sipariş yok.</p>:<table className="data-table"><thead><tr><th>Kod</th><th>Müşteri</th><th>Durum</th></tr></thead><tbody>{stats.recentOrders.map((o:any)=><tr key={o.id}><td>{o.orderCode}</td><td>{o.clientName}</td><td><Badge variant="secondary">{label('orderStatus',o.status)}</Badge></td></tr>)}</tbody></table>}</CardContent></Card></div></>)}</div></AppLayout>);
}
